### ISSUE TITLE
Bug in doodle app. (app crash) 

### ISSUE THREAD

**Issue by shaphir** [saifkhichi96/paint#6]
Hello,  I found two problems that are almost similar in this app.

Several times using the camera and Paint on the photo, will make the application crashes

Reproduce the bug
1.Open the app
2. Go to camera
3. Then, shoot some pictures, paint and save. The application will crashes after shoot some images

Doodle app version 3.2.0
Operating system: Oppo a57 android version 6.0.1.
Recording the bug on youtube
https://youtu.be/6E0jh-i1QDs

The app becomes crashes after saving some images from the gallery

Reproduce the bug
1.Open the app
2.Go to gallery to take image
3.Take some pictures to edit and save, after saving some images, the app will crashes

Doodle app version 3.2.0
Operating system: android version 6.0.1

Recording the bug on youtube
https://youtu.be/Agj8nt1cJcs

**Comment by saifkhichi96** [comment]
Hey @shaphir. I was not able to reproduce the bug on my device. It's a Huawei Y7 with Android 7.0.0. I'll try to reproduce this on a device whose specs match your device's, and then get back to you
